spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=lm_lifebank
    username: postgres
    password: Bengine
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: lm_lifebank
appProperties:
  code:
    c200: "200"
    c401: "401"
    c400: "400"
    c404: "404"
    c409: "409"
  messages:
    mjs1: "Se produjo un error"
    mjs2: "Usuario y/o contraseña invalido"
    mjs3: "Token invalido"
    mjs4: "No se encontraron productos"
    mjs5: "Una de las cuentas no fue encontrada"
    mjs6: "Cuentas repetidas"
    mjs7: "Una de las cuentas no pertenece al cliente"
    mjs8: "Tipo de cuenta invalida"
    mjs9: "Saldo insuficiente"
    mjs10: "Contacto no asociado."
    mjs11: "Contacto ya está asociado."
    mjs12: "JWT Invalido"
    mjs13: "Expiro la sesion."
    mjs14: "Operacion denegada."
    mjs15: "Cuenta Invalida"
    msj16: "Fecha invalida"
    msj17: "Rango de meses excede a 3 meses"
    msj18: "Operacion requiere JWT token"
    msj19: "Correo electronico no valido"
    msj20: "Beneficiario invalido"
  creditCard: "1"
  loan: "2"
  personal: "3"
  jwt:
    secret: helloWorld
    expiration-time: 1800000
